### ISSUE TITLE
error in architecture, but it appears in </architecture>

### ISSUE THREAD

**Issue by omarghoneim3** [lnis-uofu/OpenFPGA#902]
python3 openfpga_flow/scripts/run_fpga_task.py basic_tests/full_testbench/configuration_chain --show_thread_logs
 INFO (     MainThread) - Set up to run 2 Parallel threads
 INFO (     MainThread) - Currently running task basic_tests/full_testbench/configuration_chain
 INFO (     MainThread) - Created "run144" directory for current task run
 INFO (     MainThread) - Running "yosys_vpr" flow
 INFO (     MainThread) - Found 2 Architectures 3 Benchmarks & 1 Script Parameters
 INFO (     MainThread) - Created total 6 jobs
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) - Validating command line arguments
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) - Run directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run144/k4_N4_OpenFPGA_simulation/or2/MIN_ROUTE_CHAN_WIDTH
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) - Running "yosys_vpr" Flow
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Validating command line arguments
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Run directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run144/k4_N4_OpenFPGA_simulation/24clock.v/MIN_ROUTE_CHAN_WIDTH
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Running "yosys_vpr" Flow
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) - Traceback (most recent call last):
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -   File "/home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py", line 914, in <module>
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -     main()
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -   File "/home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py", line 262, in main
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -     run_yosys_with_abc()
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -   File "/home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py", line 604, in run_yosys_with_abc
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -     ys_params = create_yosys_params()
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -   File "/home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py", line 480, in create_yosys_params
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -     tree = ET.parse(args.arch_file)
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -   File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -     tree.parse(source, parser)
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -   File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) -     self._root = parser._parse_whole(source)
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) - xml.etree.ElementTree.ParseError: mismatched tag: line 320, column 2
ERROR (00_or2_MIN_ROUTE_CHAN_WIDTH) - Failed to execute openfpga flow - 00_or2_MIN_ROUTE_CHAN_WIDTH
Traceback (most recent call last):
  File "openfpga_flow/scripts/run_fpga_task.py", line 513, in run_single_script
subprocess.CalledProcessError: Command 'python3 /home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py /home/omar/OpenFPGA/openfpga_flow/vpr_arch/k4_N4_OpenFPGA_simulation.xml /home/omar/OpenFPGA/openfpga_flow/benchmarks/micro_benchmark/or2/or2.v --top_module or2 --run_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run144/k4_N4_OpenFPGA_simulation/or2/MIN_ROUTE_CHAN_WIDTH --fpga_flow yosys_vpr --openfpga_shell_template /home/omar/OpenFPGA/openfpga_flow/openfpga_shell_scripts/write_full_testbench_example_script.openfpga --openfpga_arch_file /home/omar/OpenFPGA/openfpga_flow/openfpga_arch/k4_N4_openfpga_arch.xml --openfpga_sim_setting_file /home/omar/OpenFPGA/openfpga_flow/openfpga_simulation_settings/auto_sim_openfpga.xml --openfpga_vpr_device_layout  --openfpga_fast_configuration  --power --power_tech /home/omar/OpenFPGA/openfpga_flow/tech/PTM_45nm/45nm.xml --vpr_fpga_verilog --vpr_fpga_verilog_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run144/k4_N4_OpenFPGA_simulation/or2/MIN_ROUTE_CHAN_WIDTH --vpr_fpga_x2p_rename_illegal_port --end_flow_with_test --TOP or2 --CHAN_WIDTH 300 --READ_VERILOG_OPTIONS -nolatches' returned non-zero exit status 0.

**Comment by omarghoneim3** [comment]
![Capture2](https://user-images.githubusercontent.com/109771318/202694767-29796d5d-5faa-47ce-9549-6f588579bddd.JPG)

**Comment by omarghoneim3** [comment]
<openfpga_architecture>
  <models>
     <model name="io">
      <input_ports>
        <port name="outpad"/>
      </input_ports>
      <output_ports>
        <port name="inpad"/>
      </output_ports>
    </model>
  </models>

  <tiles>
    <tile name="io" capacity="8" area="0">
      <equivalent_sites>
        <site pb_type="io"/>
      </equivalent_sites>
      <input name="outpad" num_pins="1"/>
      <output name="inpad" num_pins="1"/>
      <fc in_type="frac" in_val="0.15" out_type="frac" out_val="0.10"/>
      <pinlocations pattern="custom">
        <loc side="left">io.outpad io.inpad</loc>
        <loc side="top">io.outpad io.inpad</loc>
        <loc side="right">io.outpad io.inpad</loc>
        <loc side="bottom">io.outpad io.inpad</loc>
      </pinlocations>
    </tile>
    <tile name="clb" area="53894">
      <equivalent_sites>
        <site pb_type="clb"/>
      </equivalent_sites>
      <input name="I" num_pins="10" equivalent="full"/>
      <output name="O" num_pins="4" equivalent="none"/>
      <clock name="clk" num_pins="1"/>
      <fc in_type="frac" in_val="0.15" out_type="frac" out_val="0.10"/>
      <pinlocations pattern="spread"/>
    </tile>
  </tiles>
  
  
  <layout tileable="true">
    <auto_layout aspect_ratio="1.0">
      
      <perimeter type="io" priority="100"/>
      <corners type="EMPTY" priority="101"/>
      
      <fill type="clb" priority="10"/>
    </auto_layout>
    <fixed_layout name="2x2" width="4" height="4">
      
      <perimeter type="io" priority="100"/>
      <corners type="EMPTY" priority="101"/>
      
      <fill type="clb" priority="10"/>
    </fixed_layout>
    <fixed_layout name="4x4" width="6" height="6">
      
      <perimeter type="io" priority="100"/>
      <corners type="EMPTY" priority="101"/>
      
      <fill type="clb" priority="10"/>
    </fixed_layout>
	
    <fixed_layout name="48x48" width="50" height="50">
      
      <perimeter type="io" priority="100"/>
      <corners type="EMPTY" priority="101"/>
      
      <fill type="clb" priority="10"/>
    </fixed_layout>
    <fixed_layout name="96x96" width="98" height="98">
      
      <perimeter type="io" priority="100"/>
      <corners type="EMPTY" priority="101"/>
      
      <fill type="clb" priority="10"/>
    </fixed_layout>
  </layout>
  <device>
    <sizing R_minW_nmos="8926" R_minW_pmos="16067"/>
    
    <area grid_logic_tile_area="0"/>
    <chan_width_distr>
      <x distr="uniform" peak="1.000000"/>
      <y distr="uniform" peak="1.000000"/>
    </chan_width_distr>
    <switch_block type="wilton" fs="3"/>
    <connection_block input_switch_name="ipin_cblock"/>
  </device>
  <switchlist>
    <switch type="mux" name="0" R="551" Cin=".77e-15" Cout="4e-15" Tdel="58e-12" mux_trans_size="2.630740" buf_size="27.645901"/>
    
    <switch type="mux" name="ipin_cblock" R="2231.5" Cout="0." Cin="1.47e-15" Tdel="7.247000e-11" mux_trans_size="1.222260" buf_size="auto"/>
  </switchlist>

  <segmentlist>
    <segment name="L4" freq="1.000000" length="4" type="unidir" Rmetal="101" Cmetal="22.5e-15">
      <mux name="0"/>
      <sb type="pattern">1 1 1 1 1</sb>
      <cb type="pattern">1 1 1 1</cb>
    </segment>
  </segmentlist>

  <complexblocklist>
    <pb_type name="io">
      <input name="outpad" num_pins="1"/>
      <output name="inpad" num_pins="1"/>

      <mode name="physical" packable="false"> 
        <pb_type name="iopad" blif_model=".subckt io" num_pb="1">
          <input name="outpad" num_pins="1"/>
          <output name="inpad" num_pins="1"/>
        </pb_type>

        <interconnect>
          <direct name="outpad" input="io.outpad" output="iopad.outpad">
            <delay_constant max="1.394e-11" in_port="io.outpad" out_port="iopad.outpad"/>
          </direct>
          <direct name="inpad" input="iopad.inpad" output="io.inpad">
            <delay_constant max="4.243e-11" in_port="iopad.inpad" out_port="io.inpad"/>
          </direct>
        </interconnect>
      </mode>


      <mode name="inpad">
        <pb_type name="inpad" blif_model=".input" num_pb="1">
          <output name="inpad" num_pins="1"/>
        </pb_type>
        <interconnect>
          <direct name="inpad" input="inpad.inpad" output="io.inpad">
            <delay_constant max="9.492000e-11" in_port="inpad.inpad" out_port="io.inpad"/> 
          </direct>
        </interconnect>
      </mode>
      <mode name="outpad">
        <pb_type name="outpad" blif_model=".output" num_pb="1">
          <input name="outpad" num_pins="1"/>
        </pb_type>
        <interconnect>
          <direct name="outpad" input="io.outpad" output="outpad.outpad">
            <delay_constant max="2.675000e-11" in_port="io.outpad" out_port="outpad.outpad"/> 
          </direct>
        </interconnect>
      </mode>
      
      
      
      <power method="ignore"/>
    </pb_type>
    <pb_type name="clb">
      <input name="I" num_pins="10" equivalent="full"/>
      <output name="O" num_pins="4" equivalent="none"/>
      <clock name="clk" num_pins="1"/>
      
      <pb_type name="fle" num_pb="4">
        <input name="in" num_pins="4"/>
        <output name="out" num_pins="1"/>
        <clock name="clk" num_pins="1"/>
        
        <mode name="n1_lut4">
          
          <pb_type name="ble4" num_pb="1">
            <input name="in" num_pins="4"/>
            <output name="out" num_pins="1"/>
            <clock name="clk" num_pins="1"/>
            
            <pb_type name="lut4" blif_model=".names" num_pb="1" class="lut">
              <input name="in" num_pins="4" port_class="lut_in"/>
              <output name="out" num_pins="1" port_class="lut_out"/>
              
              <delay_matrix type="max" in_port="lut4.in" out_port="lut4.out">
                261e-12
                261e-12
                261e-12
                261e-12
              </delay_matrix>
            </pb_type>
            
            <pb_type name="ff" blif_model=".latch" num_pb="1" class="flipflop">
              <input name="D" num_pins="1" port_class="D"/>
              <output name="Q" num_pins="1" port_class="Q"/>
              <clock name="clk" num_pins="1" port_class="clock"/>
              <T_setup value="66e-12" port="ff.D" clock="clk"/>
              <T_clock_to_Q max="124e-12" port="ff.Q" clock="clk"/>
            </pb_type>
            <interconnect>
              <direct name="direct1" input="ble4.in" output="lut4[0:0].in"/>
              <direct name="direct2" input="lut4.out" output="ff.D">
	    
		<pb_type name="ff" blif_model=".latch" num_pb="1" class="flipflop">
              <input name="T" num_pins="1" port_class="T"/>
	      <input name="Sclear" num_pins="1" port_class="Sclear"/>
	      <input name="reset" num_pins="1" port_class="reset"/>
              <output name="Q" num_pins="1" port_class="Q"/>
	      <output name="QN" num_pins="1" port_class="QN"/>
              <clock name="clk" num_pins="1" port_class="clk"/>
              <T_setup value="66e-12" port="ff.D" clock="clk"/>
              <T_clock_to_Q max="124e-12" port="ff.Q" clock="clk"/>
            </pb_type>
            <interconnect>
              <direct name="direct1" input="ble4.in" output="lut4[0:0].in"/>
              <direct name="direct2" input="lut4.out" output="ff.D">
                
                <pack_pattern name="ble4" in_port="lut4.out" out_port="ff.D"/>
              </direct>
              <direct name="direct3" input="ble4.clk" output="ff.clk"/>
              <mux name="mux1" input="ff.Q lut4.out" output="ble4.out">
                
                <delay_constant max="25e-12" in_port="lut4.out" out_port="ble4.out"/>
                <delay_constant max="45e-12" in_port="ff.Q" out_port="ble4.out"/>
              </mux>
            </interconnect>
          <pb_type>
	  <mode>
          <interconnect>
            <direct name="direct1" input="fle.in" output="ble4.in"/>
            <direct name="direct2" input="ble4.out" output="fle.out[0:0]"/>
            <direct name="direct3" input="fle.clk" output="ble4.clk"/>
          </interconnect>
        </mode>
        
      </pb_type>
      <interconnect>
        <complete name="crossbar" input="clb.I fle[3:0].out" output="fle[3:0].in">
          <delay_constant max="95e-12" in_port="clb.I" out_port="fle[3:0].in"/>
          <delay_constant max="75e-12" in_port="fle[3:0].out" out_port="fle[3:0].in"/>
        </complete>
        <complete name="clks" input="clb.clk" output="fle[3:0].clk">
        </complete>
        
        <direct name="clbouts1" input="fle[3:0].out" output="clb.O"/>
      </interconnect>
</complexblocklist>
</openfpga_architecture>
